/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/pay_systems.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PaySystemsIcons {
  PaySystemsIcons._();

  static const _kFontFam = 'PaySystems';

  static const IconData mastercard = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData mir = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData visa = IconData(0xe802, fontFamily: _kFontFam);
}
