/// Flutter icons OutlineIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OutlineIcons
///      fonts:
///       - asset: fonts/OutlineIcons.ttf
///
/// 
///
// ignore_for_file: lines_longer_than_80_chars
library;
import 'package:flutter/widgets.dart';

class OutlineIcons {
  OutlineIcons._();

  static const _kFontFam = 'Outline';
  static const String? _kFontPkg = null;

  static const IconData add = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData anceta = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowdown = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowleft = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowright = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowup_1 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowup = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cam = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cardimage = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData case_icon = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_all = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check2_all = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check2 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkmark = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clean = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData del = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData face_id = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileearmark = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileearmarkarrowup = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData horizontal = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData infocircle = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loading = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messageoutline = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newspaper = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData percongroup = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData personcircle = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData questionmark = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData top = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usersoutline = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
