/// Flutter icons SolidIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SolidIcons
///      fonts:
///       - asset: fonts/SolidIcons.ttf
///
/// 
///
// ignore_for_file: lines_longer_than_80_chars

import 'package:flutter/widgets.dart';

class SolidIcons {
  SolidIcons._();

  static const _kFontFam = 'Solid';
  static const String? _kFontPkg = null;

  static const IconData bankcard = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendarcircle = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendarsearch = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cardadd = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cardimagefill = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData case_icon = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData change = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkmarck = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clean = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_badge = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudremovebulk = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData del = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directnormal = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emptywalletremove = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emptywallettime = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fileearmarkfill = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fullscreen = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microoff = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microon = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microphone = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microphoneslash = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData multiplay = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mute = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newspaper = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData percongroup = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData personcircle = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_1 = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phonedown = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photocam = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData screenmirroring = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData searchstatus = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phonedownfilled = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timer = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData useroctagon = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userremove = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videocamslash = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData walletcheck = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videocam = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamation_circle_fill = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
