import 'package:flutter/material.dart';

import 'package:flutter_spiks_test/core/values/colors/references/color_refs.dart';

class ColorSchemeM3 {
  static final ColorScheme lightScheme = ColorScheme(
    brightness: Brightness.light,
    primary: ColorRefs.keyPrimary,
    onPrimary: ColorRefs.primary[100]!,
    primaryContainer: ColorRefs.primary[90],
    onPrimaryContainer: ColorRefs.primary[10],
    secondary: ColorRefs.secondary[40]!,
    onSecondary: ColorRefs.secondary[100]!,
    secondaryContainer: ColorRefs.secondary[90],
    onSecondaryContainer: ColorRefs.secondary[10],
    tertiary: ColorRefs.tertiary[40], // also ColorRefs.primary[40],
    onTertiary: ColorRefs.tertiary[100],
    tertiaryContainer: ColorRefs.tertiary[90],
    onTertiaryContainer: ColorRefs.tertiary[10],
    error: ColorRefs.error[40]!,
    onError: ColorRefs.error[100]!,
    errorContainer: ColorRefs.error[90],
    onErrorContainer: ColorRefs.error[10],
    outline: ColorRefs.neutralVariant[50],
    background: ColorRefs.primary[99]!,
    onBackground: ColorRefs.neutral[10]!,
    surface: ColorRefs.primary[99]!,
    onSurface: ColorRefs.neutral[10]!,
    surfaceVariant: ColorRefs.neutralVariant[90],
    onSurfaceVariant: ColorRefs.neutralVariant[30],
    inverseSurface: ColorRefs.neutral[20],
    onInverseSurface: ColorRefs.neutral[95],
    inversePrimary: ColorRefs.primary[30],
    shadow: ColorRefs.primary[0],
    surfaceTint: ColorRefs.primary[40],
    outlineVariant: ColorRefs.neutralVariant[80],
    scrim: ColorRefs.primary[0],
  );

  static final ColorScheme darkScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: ColorRefs.primary[30]!,
    onPrimary: ColorRefs.primary[20]!,
    primaryContainer: ColorRefs.primary[30],
    onPrimaryContainer: ColorRefs.primary[90],
    secondary: ColorRefs.secondary[80]!,
    onSecondary: ColorRefs.secondary[20]!,
    secondaryContainer: ColorRefs.secondary[30],
    onSecondaryContainer: ColorRefs.secondary[90],
    tertiary: ColorRefs.tertiary[30],
    onTertiary: ColorRefs.tertiary[20],
    tertiaryContainer: ColorRefs.tertiary[30],
    onTertiaryContainer: ColorRefs.tertiary[90],
    error: ColorRefs.error[80]!,
    onError: ColorRefs.error[20]!,
    errorContainer: ColorRefs.error[30],
    onErrorContainer: ColorRefs.error[90],
    outline: ColorRefs.neutralVariant[60],
    background: ColorRefs.neutral[10]!,
    onBackground: ColorRefs.neutral[90]!,
    surface: ColorRefs.neutral[10]!,
    onSurface: ColorRefs.neutral[80]!,
    surfaceVariant: ColorRefs.neutralVariant[30],
    onSurfaceVariant: ColorRefs.neutralVariant[80],
    inverseSurface: ColorRefs.neutral[90],
    onInverseSurface: ColorRefs.neutral[10],
    inversePrimary: ColorRefs.primary[40],
    shadow: ColorRefs.primary[0],
    surfaceTint: ColorRefs.primary[30],
    outlineVariant: ColorRefs.neutralVariant[30],
    scrim: ColorRefs.primary[0],
  );
}
